# Generated by Django 3.1.1 on 2020-10-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201031_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='doctors_prescription',
            field=models.ImageField(default='default.jpg', upload_to='prescription_pics'),
        ),
    ]
