# Generated by Django 3.1.1 on 2020-10-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_donation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='City',
            field=models.CharField(max_length=100),
        ),
    ]
