# Generated by Django 3.1.1 on 2020-10-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201031_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='doctors_prescription',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
