# Generated by Django 3.1.1 on 2020-10-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201031_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='weight',
            field=models.CharField(default='light', max_length=100),
        ),
    ]
