# Generated by Django 3.1.1 on 2020-10-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201031_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='doctors_prescription',
            field=models.ImageField(upload_to='prescription_pics'),
        ),
    ]
